
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqcpxljiaxletrqxcnsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxY3B4bGppYXhsZXRycXhjbnNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMzI0MjcsImV4cCI6MjA1NzgwODQyN30.n1ibH3YjNJi5Xefe9LNWGJhqJgDUMrFRQIosqgrmc8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Real-time updates are enabled for:
// - flashcards
// - quiz_results

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
